name: Build and Upload container
on:
  pull_request:
    branches:
      [main]
env:
  docker_username: loosemoledevops
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
  KUBECONFIG_TEST: ${{ secrets.KUBECONFIG_TEST }}
jobs:
  staging-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Create kubeconfig
        run: echo "$KUBECONFIG_TEST" | base64 -d > kubeconfig
      - name: Setup staginng manifests
        run: bash ci/setup-staging.sh
      - name: Apply K8s manifests
        run: kubectl --kubeconfig kubeconfig apply -f ./k8s-manifests/test/
      - name: Wait a little, for k8s
        run: sleep 15
      - name: Test up-status of Staging
        run: bash ci/test_test_connection.sh
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Build images
        run: bash ci/docker-build.sh
      - name: Push images
        run: bash ci/docker-push.sh
  curl-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Test uptime
        run: bash ci/test_connection.sh
